### ISSUE TITLE
Deleting Code and Formatting Incorrectly

### ISSUE THREAD

**Issue by DhruveShah** [SeanJM/atom-css-clean#30]
It was deleting some of my sass inside a selector when it had two comments at the start of the selector, and after removing the comments, and trying to clean the sass, it turned the following:
`.main-menu_cntr {`
          `background: $black;`
`          color: $white;`
`          border-top-left-radius: 30px;`
`          border-bottom-left-radius: 30px;`
`          position: absolute;`
`          top: 86px;`
`          padding-right: calc(50% - #{$biggest}/2 + #{$gapsize});`
`          right: 0;`
          
`          @include breakpoint($biggest) {`
`    				padding-right: $gapsize;`
`    			}`
`        }`
into:
`.main-menu_cntr {`
`          position                  : absolute;`
`          top                       : 86px;`
`          color                     : $white;`
`          border-top-left-radius    : 30px;`
`          border-bottom-left-radius : 30px;`
`          background                : $black;`
          
`          padding-right: calc(50% - #{$biggest}/2 + #{$gapsize}); right: 0; @include breakpoint($biggest) {`
`            padding-right : $gapsize;`
`          }`
`        }`

**Comment by SeanJM** [comment]
Can you show the SASS for all the steps?

**Comment by DhruveShah** [comment]
The sass is there, its just pasting without most of the spaces

The first block of code is the original sass, and the second block is the sass that got cleaned

**Comment by SeanJM** [comment]
Thank you.

**Comment by voznik** [comment]
it works wrong! I have following scss: 
before:
```css
img {
    padding: 10px;
    @include media-breakpoint-up(md) {
      padding: 1rem;
    }
}
```
after *css clean*:
```css
img {
    @include   media-breakpoint-up(md);
    padding  : 10px;
  }
```
