### ISSUE TITLE
`will-change: transform;` and everything below it gets deleted!

### ISSUE THREAD

**Issue by krabbypattified** [SeanJM/atom-css-clean#40]
Here's my css file:

```css
.DetailContent {
  bottom          : 0;
  border-radius   : 6px 6px 0 0;
  flex-direction  : column;
  will-change: transform; 
  justify-content : flex-start;
}

```
